# Generated by Django 6.0.4 on 2026-04-24 11:12

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
