# Generated by Django 6.0.4 on 2026-04-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_chunk_embedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
